version: "3"
services:

  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./www:/usr/share/nginx/html